name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env: TEST1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Read env variable
        run: |
          echo "testing workflow env variable directly: ${{ vars.TEST1 }}"
          echo "testing env secret: ${{ secrets.SUPER_SECRET }}"
          echo "testing job specific variable $MY_IMAGE_NAME"
