name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: soen287project

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build stage
        run: |
          echo "Building docker image"
          docker build -t ${{env.IMAGE_NAME}}
